CREATE DATABASE IF NOT EXISTS dev0;

USE dev0;

DROP TABLE IF EXISTS songs;
DROP TABLE IF EXISTS artists;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS made_by;
DROP TABLE IF EXISTS playlists;
DROP TABLE IF EXISTS playlist_songs;

 
